name 'virtuoso-opensource-7'
maintainer 'Takeo Kunishima'
maintainer_email 't.kunishi@gmail.com'
license 'MIT'
description 'Installs/Configures virtuoso-opensource-7'
long_description 'Installs/Configures virtuoso-opensource-7'
version '0.1.0'

depends 'build-essential'
depends 'git'
depends 'openjdk'
depends 'python'
