name 'vagrant-virtuoso'
maintainer 'Takeo Kunishima'
maintainer_email 't.kunishi@gmail.com'
license 'MIT'
description 'Installs/Configures vagrant-virtuoso'
long_description 'Installs/Configures vagrant-virtuoso'
version '0.1.0'

depends 'apt'
depends 'build-essential'
depends 'git'
