name 'vagrant-virtuoso'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures vagrant-virtuoso'
long_description 'Installs/Configures vagrant-virtuoso'
version '0.1.0'
